### ISSUE TITLE
ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by josephshirima** [javadev/underscore-java#270]
Try to use it on Spring Boot App on rabbitmq consumer method handler. But am getting this exception. What is may be a possible causes?

**My Code**

@RabbitListener(queues = "my.queue.name")
	public void messageHandle(String content) {
		  Map<String,Object> map = U.fromXmlMap(content);
		  Map<String,Object> root = (Map<String, Object>) map.get("Message");
		  String jsonContent = U.toJson(root);
		  return jsonContent.getBytes();
}

**Exception ::**

java.lang.ExceptionInInitializerError: null
at com.github.underscore.lodash.U.fromXmlMap(U.java:2142) ~[underscore-1.58.jar:na]
at com.github.underscore.lodash.U.fromXmlMap(U.java:2137) ~[underscore-1.58.jar:na]
...
....
....
....

Caused by: java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.setAttribute(Unknown Source) ~[xercesImpl-2.9.1.jar:na]
at com.github.underscore.lodash.Xml$Document.createDocument(Xml.java:1418) ~[underscore-1.58.jar:na]
at com.github.underscore.lodash.Xml$Document.access$000(Xml.java:1392) ~[underscore-1.58.jar:na]
at com.github.underscore.lodash.Xml.(Xml.java:65) ~[underscore-1.58.jar:na]

**Comment by javadev** [comment]
Thank you for the report.

It was already fixed today.

**Comment by josephshirima** [comment]
Thank you for feedback, But when does the Version 1.59 be available on maven repo? Still getting the Error with version 1.58.

**Comment by javadev** [comment]
It will be available in October.

**Comment by javadev** [comment]
The new version was released today. 🎉
